name       : haskell-path
version    : 0.6.1
release    : 2
source     :
    - https://hackage.haskell.org/package/path-0.6.1/path-0.6.1.tar.gz : 4b8bd85a13395b4240c639b9cf804371854d5dac69158f661068bd3089a25e59
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support for well-typed paths.
description: "Support for well-typed paths. \n"
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-exceptions
setup      : |
    sed -i "s|0.9|0.11|g" path.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
