name       : haskell-path
version    : 0.5.12
release    : 1
source     :
    - http://hackage.haskell.org/package/path-0.5.12/path-0.5.12.tar.gz : 52f0dae7e3d72d26fa62ff55de65b6697744dd0c5b96f48625cb00df1cf1055d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support for well-typed paths.
description: |
    Support for well-typed paths. 
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-exceptions
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
